training:
  start_date: '2018-01-01'
  end_date: '2024-07-20'
  epochs: 100
  batch_size: 32
  validation_split: 0.2
  early_stopping_patience: 10

model:
  sequence_length: 60
  lstm_units: [50, 50, 50]
  dropout_rate: 0.2
  learning_rate: 0.001

data:
  features:
    - Close
    - MA5
    - MA20
    - RSI
    - Volatility
  target: Close

monitoring:
  metrics:
    - mae
    - mape
    - rmse
  log_level: INFO
